[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
oft = "SquidjXLN8SX6wkLqK2miXGGciCGUrVqEtasjiZ2UWc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/maga/secure_keys/Gihun3g2XijWDVGn42SbR8hwyYpWr9FaJhWHth5wcAUc.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
